<?php

namespace AppBundle\Repository;

/**
 * HopitaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HopitaleRepository extends \Doctrine\ORM\EntityRepository
{
}
