# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/Maintenance, roles: ROLE_USER }
        - { path: ^/article/*, roles: ROLE_USER }
        - { path: ^/categorie/*, roles: ROLE_USER }
        - { path: ^/Service/*, roles: ROLE_USER }
        - { path: ^/Hopitale/*, roles: ROLE_USER }
        - { path: ^/Statistique, roles: ROLE_USER }
    access_denied_url: /login
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: AppBundle:User, property: email }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
